services:
    mary:
        build:
            context: ..
            dockerfile: .docker/Dockerfile
            target: base
        tty: true
        volumes:
            - ../:/app:cached
        ports:
            - 8018:8000
            - 5174:5174
